services:
  db:
    image: postgres:latest
    container_name: clean-arch-db
    environment:
      POSTGRES_DB: MyCleanArchDb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d MyCleanArchDb"]
      interval: 5s
      timeout: 5s
      retries: 5

  webapi:
    image: clean-arch-webapi
    build:
      context: .
      dockerfile: src/WebApi/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5130
      - ConnectionStrings__DefaultConnection=Host=db;Database=MyCleanArchDb;Username=postgres;Password=password
    ports:
      - "5130:5130"
    depends_on:
      db:
        condition: service_healthy

